layout={
  main={

    LuaEditor,
    id="editor",
    text= "",
    layout_width="fill",
    layout_height="fill",
    --layout_weight=1 ,
    --gravity="top"

  },

  create={
    LinearLayout ,
    layout_width="fill",
    orientation=1,
    {
      TextView,
      id="create_t",
      text=dir,
      layout_width="fill",
      paddingLeft=20,
    },
    {
      EditText,
      id="create_e",
      layout_width="fill",
      paddingLeft=20,
    },
    {
      Button,
      text="确定",
      layout_width="fill",
      onClick="create"
    },
  },

  help={
    ScrollView,
    {
      LinearLayout,
      layout_width="fill",
      orientation=1,
      paddingLeft=20,
      {
        TextView,
        autoLinkMask=1,
        movementMethod=LinkMovementMethod.getInstance(),
        linkTextColor="#0000ff",
        layout_width="fill",
        text=about,
        textIsSelectable=true
      },
      {
        TextView,
        autoLinkMask=1,
        movementMethod=LinkMovementMethod.getInstance(),
        linkTextColor="#0000ff",
        layout_width="fill",
        text=help1,
        textIsSelectable=true
      },
      {
        TextView,
        linkTextColor="#0000ff",
        layout_width="fill",
        text=help2,
        textIsSelectable=true
      },
    }
  },

  build={
    ScrollView ,
    {
      LinearLayout,
      orientation=1,
      layout_width="fill",
      paddingLeft=20,
      {
        TextView,
        text="脚本路径"
      },
      {
        EditText,
        id="luaPath",
        layout_width="fill",
        singleLine=true,
      },
      {
        TextView,
        text="包名称"
      },
      {
        EditText,
        id="packageName",
        layout_width="fill",
        singleLine=true,
      },
      {
        TextView,
        text="程序名称"
      },
      {
        EditText,
        id="appName",
        layout_width="fill",
        singleLine=true,
      },
      {
        TextView,
        text="程序版本"
      },
      {
        EditText,
        id="appVer",
        layout_width="fill",
        singleLine=true,
      },
      {
        TextView,
        text="apk路径"
      },
      {
        EditText,
        id="apkPath",
        layout_width="fill",
        singleLine=true,
      },
      {
        TextView,
        text="打包使用debug签名",
        id="status"
      },
      {
        Button,
        text="确定",
        layout_width="fill",
        onClick="buildfile"
      },
    }
  },
  project={
    ScrollView ,
    {
      LinearLayout,
      orientation=1,
      layout_width="fill",
      padding="10dp",
      {
        TextView,
        text="程序名称"
      },
      {
        EditText,
        id="project_appName",
        text="demo",
        layout_width="fill",
        singleLine=true,
      },
      {
        TextView,
        text="包名称"
      },
      {
        EditText,
        id="project_packageName",
        text="com.androlua.demo",
        layout_width="fill",
        singleLine=true,
      },
      {
        Button,
        text="确定",
        layout_width="fill",
        onClick="create_project"
      },
    }
  }
}
